app:
  debug: True
  secret_key: 'secret_key'
  https_mode: "adhoc"

  # https_mode: No  # http only, not recommended

  # https_mode: "cert"
  # cert:
    # cert: "cert.pem"
    # key: "key.pem"


db:
  type: "file"
  file: "files.db"

  # type: "details"
  host: null
  port: null
  username: null
  password: null
  database: null

  # type: "string"
  conn_str: null